apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: kapp-deployment
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: kapp
        spec:
            containers:
                - name: kapp
                  image: rsysio/kapp:1.0.1
                  ports:
                      - containerPort: 8877
