apiVersion: v1
kind: Service
metadata:
    name: kapp
    labels:
        run: kapp
spec:
    type: NodePort
    ports:
        - port: 8877
          nodePort: 31877
          protocol: TCP
    selector:
        app: kapp
