workspace:
    base: /go
    path: src/github.com/rsysio/kapp

pipeline:
    build:
        image: golang
        commands:
            - go get
            - go build
    publish:
        image: ubuntu
        commands:
            - echo hello
