workspace:
    base: /go
    path: src/github.com/rsysio/kapp

pipeline:

    build:
        image: golang:latest
        commands:
            - go get github.com/Masterminds/glide
            - go install github.com/Masterminds/glide
            - glide install
            - make build

    publish:
        image: plugins/docker
        repo: rsysio/kapp
        tags:
            - 1.0.0
            - latest
        secrets:
            - docker_username
            - docker_password
