workspace:
    base: /go
    path: src/github.com/rsysio/kapp

pipeline:

    build:
        image: golang:latest
        commands:
            - ls -l /go
            - go get github.com/Masterminds/glide
            - go install github.com/Masterminds/glide
            - glide install
            - go build

    publish:
        image: ubuntu
        commands:
            - echo hello
