---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: kapp-deployment
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: kapp
        spec:
            containers:
                - name: kapp
                  image: rsysio/kapp:1.0.2
                  ports:
                      - containerPort: 8877
---
apiVersion: v1
kind: Service
metadata:
    name: kapp
    labels:
        run: kapp
        service: http
spec:
    type: NodePort
    ports:
        - port: 8877
          nodePort: 31877
          protocol: TCP
    selector:
        app: kapp
