---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kapp
    spec:
      containers:
        - name: kapp
          image: rsysio/kapp:1.0.3
          ports:
            - containerPort: 8877
---
apiVersion: v1
kind: Service
metadata:
  name: kapp
  labels:
    run: kapp
    service: http
spec:
  type: NodePort
  ports:
    - name: http
      port: 8877
      protocol: TCP
  selector:
    app: kapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kapp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kapp.rsys.io
    http:
      paths:
        - backend:
            serviceName: kapp
            servicePort: 80
